### ISSUE TITLE
Can not build avatar with AAO version 1.7.5~ imported

### ISSUE THREAD

**Issue by yuka2878** [anatawa12/AvatarOptimizer#1133]
英語を使ってごめんなさい
When I import AAO: Avatar Optimizer (after version 1.7.5),build avatar will fail.
And I need to change AAO's version to 1.7.4 to upload my avatar.
I use new unity project and only import liltoon, AAO and avatar's package.

Unity log by ConsoleLogSaver : https://67.gigafile.nu/1112-c067011b00db5b5023a29c05c6f64bda3

**Comment by anatawa12** [comment]
There's no problem with English.

The main error is the following error and it looks bug of burst compiler, C# compiler, or Unity.

Could you try reinstalling Unity?

```
Processing assembly Library/Bee/artifacts/1900b0aP.dag/com.anatawa12.avatar-optimizer.runtime.dll, with 109 defines and 201 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessor, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessor
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
zzzUnity.Burst.CodeGen.BurstILPostProcessor: ILPostProcessor has thrown an exception: System.InvalidOperationException: Internal compiler error for Burst ILPostProcessor on com.anatawa12.avatar-optimizer.runtime. Exception: System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(Stream stream, ReaderParameters parameters)
   at zzzUnity.Burst.CodeGen.AssemblyResolver.LoadFromStream(Stream peStream, Stream pdbStream, ISymbolReaderProvider customSymbolReader)
   at zzzUnity.Burst.CodeGen.BurstILPostProcessor.Process(ICompiledAssembly compiledAssembly)
   at zzzUnity.Burst.CodeGen.BurstILPostProcessor.Process(ICompiledAssembly compiledAssembly)
   at Unity.ILPP.Runner.PostProcessingPipeline.PostProcessAssemblyAsync(PostProcessAssemblyRequest request, Action`2 progressSink)
PostProcessing failed: System.InvalidOperationException: Internal compiler error for Burst ILPostProcessor on com.anatawa12.avatar-optimizer.runtime. Exception: System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(Stream stream, ReaderParameters parameters)
   at zzzUnity.Burst.CodeGen.AssemblyResolver.LoadFromStream(Stream peStream, Stream pdbStream, ISymbolReaderProvider customSymbolReader)
   at zzzUnity.Burst.CodeGen.BurstILPostProcessor.Process(ICompiledAssembly compiledAssembly)
   at zzzUnity.Burst.CodeGen.BurstILPostProcessor.Process(ICompiledAssembly compiledAssembly)
   at Unity.ILPP.Runner.PostProcessingPipeline.PostProcessAssemblyAsync(PostProcessAssemblyRequest request, Action`2 progressSink)
   at Unity.ILPP.Runner.PostProcessingService.PostProcessAssembly(PostProcessAssemblyRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context)
Unhandled Exception: System.InvalidOperationException: Post processing failed
   at Unity.ILPP.Trigger.TriggerApp.<ProcessArgumentsAsync>d__1.MoveNext() + 0xf74
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at Unity.ILPP.Trigger.TriggerApp.<ProcessArgumentsAsync>d__1.MoveNext() + 0x1149
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Unity.ILPP.Trigger.TriggerApp.<RunAsync>d__0.MoveNext() + 0xc7
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Program.<<Main>$>d__0.MoveNext() + 0x1a3
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Program.<Main>(String[]) + 0x20
   at Unity.ILPP.Trigger!<BaseAddress>+0x47849b
```

**Comment by yuka2878** [comment]
I try to reinstall unity, VCC and repair visual studio tool, it still can't work.
And I update burst from 1.8.12 to 1.8.17, the problem is solved.
Thank you for your help.

**Comment by anatawa12** [comment]
Oh it was burst side of problem...

It might be good to clear global upm cache since burst compiler of your global cache might be broken: https://docs.unity3d.com/2022.3/Documentation/Manual/upm-cache.html
